include: package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
linter:
    rules:
        public_member_api_docs: false
        require_trailing_commas: false
        lines_longer_than_80_chars: false
        always_use_package_imports: false
        prefer_relative_imports: true